version: "3.1"
services:
  web:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
  db:
    image: mysql:8.0
    platform: linux/amd64 # Ensures compatibility on Apple Silicon
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: InventoryManagement
    ports:
      - "3307:3306"

